# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy With npm_i

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name: Add EC2 Host Key to known_hosts
          run: |
            mkdir -p ~/.ssh
            ssh-keyscan -H ec2-3-1-208-37.ap-southeast-1.compute.amazonaws.com >> ~/.ssh/known_hosts

        - name: Deploy to EC2
          run: |
            echo "$SSH_PRIVATE_KEY" > ./dev_2.pem
            chmod 400 ./dev_2.pem
            ssh -i ./dev_2.pem ubuntu@ec2-3-1-208-37.ap-southeast-1.compute.amazonaws.com "cd /home && ./deploy_fe_with_npmi.sh"
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
